apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: frontend

images:
  - name: sprysio/efarm-frontend
    newTag: develop-40ccd5fcd5a0520b38da4d1e1b7559a431469b2e
