apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: frontend

images:
  - name: sprysio/efarm-frontend
    newTag: develop-69535782edb2682635d162578f6690cdc99b23e1
