apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: frontend

images:
  - name: sprysio/efarm-frontend
    newTag: develop-7173908ee9a7d4b1147edb19147f3cc754395d44
