apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: frontend

images:
  - name: sprysio/efarm-frontend
    newTag: develop-2758376ae35bf1427f4299e1f463fd0133e87d86
