apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: frontend

images:
  - name: sprysio/efarm-frontend
    newTag: develop-62eed23512b151460ef5fe2b054ff9203f3f65f4
